/**
 * Activates dark mode by adding the style generated by ConstructDarkModeStyle
 * function to the document tree, and removing blinds storage
 * 
 * @param: `NULL`
 * @returns `void`
 */
export function activateDarkMode()
{
    if (blindsStylesFinal === undefined) {
        setBlindsStylesFinal(constructDarkModeStyle());
    }

    let styleTag;
    if (document.querySelector(`style#${blindsStyleId}`) === null) {
        styleTag = document.createElement("style");
        styleTag.setAttribute("id", blindsStyleId);
    } else {
        styleTag = document.querySelector(`style#${blindsStyleId}`);
    }
    styleTag.textContent = blindsStylesFinal;

    document.head.appendChild(styleTag);
    setStorage();
    switchIcon();
}
