/**
 * Activates dark mode by adding the style generated by ConstructDarkModeStyle
 * function to the document tree, and removing blinds storage
 * 
 * @param: `NULL`
 * @returns `void`
 */
export function activateDarkMode()
{
    let styles = constructDarkModeStyle();

    let styleTag = document.createElement("style");
    styleTag.setAttribute("id", blindsDomStyleId);
    styleTag.textContent = styles;

    document.head.appendChild(styleTag);
    setStorage();
    switchIcon();
}
