/**
 * Deactivates the dark mode if active by removing the style generated by
 * ConstructDarkModeStyle function in the document tree,
 * and removing blinds storage
 * @param: `NULL`
 * @returns `void`
 */
export function deactivateDarkMode()
{
    let style = document.querySelector(`style#${blindsStyleId}`);

    if (style != null) {
        document.head.removeChild(style);
        deleteStorage();
        switchIcon();
    }
}
